version: '3.8'

services:
  mininet:
    build:
      context: .
      dockerfile: mininet.dockerfile
    image: mininet-lab:latest
    container_name: mininet-lab
    privileged: true
    network_mode: host
    volumes:
      - /home/astro/AppData/mininet:/AppData/mininet
      - /lib/modules:/lib/modules:ro
      - /sys/kernel/debug:/sys/kernel/debug:rw
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /bin/bash /start.sh
